disable check

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -43,16 +43,16 @@ jobs:
         with:
           exclude_inputs: bundle_id,display_name
 
-      - name: Validate IPA URL
-        run: |
-          curl -L -r 0-1023 -o sample.part "${{ inputs.ipa_url }}" > /dev/null 2>&1
+      # - name: Validate IPA URL
+      #   run: |
+      #     curl -L -r 0-1023 -o sample.part "${{ inputs.ipa_url }}" > /dev/null 2>&1
           
-          file_type=$(file --mime-type -b sample.part)
+      #     file_type=$(file --mime-type -b sample.part)
 
-          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
-            echo "::error::Validation failed: The file is not a valid IPA file. Detected type: $file_type."
-            exit 1
-          fi
+      #     if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
+      #       echo "::error::Validation failed: The file is not a valid IPA file. Detected type: $file_type."
+      #       exit 1
+      #     fi
 
       - name: Install Dependencies
         run: brew install make ldid
